// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQqAyStRMoy-duwLsJLwfaRK8XOgEbJJo',
    appId: '1:781484222896:web:93e8c5f94f1beed0bfce75',
    messagingSenderId: '781484222896',
    projectId: 'demochatapp-4ab1b',
    authDomain: 'demochatapp-4ab1b.firebaseapp.com',
    databaseURL: 'https://demochatapp-4ab1b-default-rtdb.firebaseio.com',
    storageBucket: 'demochatapp-4ab1b.appspot.com',
    measurementId: 'G-HGVVYNGE8E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDW-uKgIhY1lPCGuQfijNSyWe3FVhNeg1w',
    appId: '1:781484222896:android:804561bca305db0bbfce75',
    messagingSenderId: '781484222896',
    projectId: 'demochatapp-4ab1b',
    databaseURL: 'https://demochatapp-4ab1b-default-rtdb.firebaseio.com',
    storageBucket: 'demochatapp-4ab1b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCU7xS42HJqqYxW8K9iY2qD6wb8zdG8XYo',
    appId: '1:781484222896:ios:5697b553e73e37d4bfce75',
    messagingSenderId: '781484222896',
    projectId: 'demochatapp-4ab1b',
    databaseURL: 'https://demochatapp-4ab1b-default-rtdb.firebaseio.com',
    storageBucket: 'demochatapp-4ab1b.appspot.com',
    iosClientId: '781484222896-ffe7npc7tmdcqjr05vml5rn0oc6rch7q.apps.googleusercontent.com',
    iosBundleId: 'com.example.demoChatApp',
  );
}
